name: deploy to github pages

on:
  push:
    branches:
      - main

jobs:
  deploy-to-github-pages:
    name: deploy to github pages
    runs-on: ubuntu-latest

    steps:
      - name: build-statics
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install
      - run: npm run build
      - run: npm run build-storybook

      - name: deploy to github pages
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: ./dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}